Add dependency on PCCTS-generated files for compiling ccccmain
The missing dependency was sometimes (on the order of one in four times
on my system) visible when using `make --shuffle` from GNU Make 4.4,
resulting in something like this:

  ccccmain.cc:33:10: fatal error: CParser.h: No such file or directory
     33 | #include "CParser.h"
        |          ^~~~~~~~~~~
  compilation terminated.

It's a bit awkward to handle the way that generating the Ada files is
disabled, but I tried to roughly match the way that `ADA_SPAWN_OBJ` and
`ADA_LANG_DEFINE` are commented out.